#!/bin/bash

while read -r item; do

    item=${item#./}

    # files to skip
    [[ $item == $(basename "$0") ]] && continue
    [[ $item == README.md ]] && continue
    [[ $item =~ ^\. ]] && continue

    src="$PWD/$item"
    src="${src/$HOME\/}"
    dst="$HOME/.$item"

    if [[ -L $dst ]]; then

        STAT_FORMAT_FLAG="-c"
        if [[ $OSTYPE =~ ^darwin ]]; then
            STAT_FORMAT_FLAG="-f"
        fi
            
        if [[ $(stat $STAT_FORMAT_FLAG "%i" -L "$dst") == $(stat $STAT_FORMAT_FLAG "%i" -L "$item") ]]; then
            # destination exists and has same inode as source
            continue
        fi

        rm "$dst"

    elif [[ -e $dst ]]; then

        mv -f "$dst" "$dst.bak"

    fi

    echo "$dst -> $src"
    ln -s "$src" "$dst"

done < <((find . -mindepth 1 -maxdepth 1 -print))
